"""
W3C::Rnodes::AclSqlObjects:
  database: w3c
  tables: userDetails, groupDetails, hierarchy, idInclusions, acls, ids, uris
generated on: Wed Jul 17 12:02:43 EDT 2002
          by: $Header$
-------------------------------------------------------------------------
mr-pink:/usr/local/perl/modules/W3C/Rnodes/bin$ ../../Database/bin/object_maker -p ../../../Conf/chacl.prop w3c -n W3C::Rnodes::AclSqlObjects -h ../AclSqlObjects.html -m {userDetails.status=>undef,  \
    userDetails.emailUrisId=>uris.id,  \
    userDetails.phonesId=>undef,  \
    groupDetails.acRep=>undef,  \
    hierarchy.sponsor=>ids.id,  \
    hierarchy.stops=>undef,  \
    idInclusions.g=>undef,  \
    idInclusions.id=>ids.id,  \
    uris.acl=>undef,  \
    acls.id=>undef,  \
    idInclusions.groupId=>undef \
    } userDetails groupDetails hierarchy idInclusions acls ids uris py: /usr/local/perl/modules/W3C/Rnodes/AclSqlObjects.py
-------------------------------------------------------------------------
"""
_AllTables = { 'ids' : { '-table' : 'ids',
                           '-index' : { 'u_value' : { '-unique' : '1',
                                                        '-sequence' : [ 'value' ],
                                                        '-fields' : { 'value' : '0' } },
                                         'value' : { '-unique' : '1',
                                                      '-sequence' : [ 'type',
                                                                       'value' ],
                                                      '-fields' : { 'value' : '1',
                                                                     'type' : '0' } },
                                         'value_idx' : { '-unique' : '',
                                                          '-sequence' : [ 'type',
                                                                           'value' ],
                                                          '-fields' : { 'value' : '1',
                                                                         'type' : '0' } } },
                           '-class' : 'W3C::Rnodes::AclSqlObjects::ids',
                           '-fieldOrder' : [ 'id',
                                              'stops',
                                              'type',
                                              'value',
                                              'pubKey',
                                              'expire',
                                              'info',
                                              'last',
                                              'orgId',
                                              'sponsor',
                                              'fmp' ],
                           '-fields' : { 'stops' : { '-size' : '10',
                                                       '-type' : 0,
                                                       '-null' : 1,
                                                       '-default' : '0' },
                                          'value' : { '-size' : '40',
                                                       '-type' : 4,
                                                       '-default' : '' },
                                          'fmp' : { '-size' : '1',
                                                     '-type' : 0,
                                                     '-null' : 1 },
                                          'info' : { '-size' : '80',
                                                      '-type' : 4,
                                                      '-null' : 1 },
                                          'pubKey' : { '-size' : "NULL",
                                                        '-type' : 5,
                                                        '-null' : 1 },
                                          'sponsor' : { '-size' : '32',
                                                         '-type' : 4,
                                                         '-null' : 1 },
                                          'last' : { '-type' : 10,
                                                      '-null' : 1 },
                                          'id' : { '-size' : '10',
                                                    '-type' : 0 },
                                          'orgId' : { '-size' : '10',
                                                       '-type' : 0,
                                                       '-default' : '0' },
                                          'type' : { '-size' : '1',
                                                      '-type' : 3,
                                                      '-default' : '' },
                                          'expire' : { '-type' : 7,
                                                        '-null' : 1 } },
                           '-primaryKey' : 'id' },
                'idInclusions' : { '-table' : 'idInclusions',
                                    '-index' : { 'PRIMARY' : { '-unique' : '1',
                                                                 '-sequence' : [ 'id',
                                                                                  'groupId' ],
                                                                 '-fields' : { 'groupId' : '1',
                                                                                'id' : '0' } } },
                                    '-class' : 'W3C::Rnodes::AclSqlObjects::idInclusions',
                                    '-fieldOrder' : [ 'id',
                                                       'groupId',
                                                       'type',
                                                       'g' ],
                                    '-fields' : { 'groupId' : { '-size' : '10',
                                                                  '-type' : 0,
                                                                  '-default' : '0' },
                                                   'ARRAY(0x844af98)' : {},
                                                   'g' : { '-size' : '11',
                                                            '-type' : 0,
                                                            '-null' : 1 },
                                                   'id' : { '-target' : [ 'ids',
                                                                            'id' ],
                                                             '-size' : '10',
                                                             '-type' : 0,
                                                             '-default' : '0' },
                                                   'type' : { '-size' : '1',
                                                               '-type' : 3,
                                                               '-default' : '' } },
                                    '-primaryKey' : [ 'id',
                                                       'groupId' ] },
                'hierarchy' : { '-table' : 'hierarchy',
                                 '-index' : { 'PRIMARY' : { '-unique' : '1',
                                                              '-sequence' : [ 'super',
                                                                               'sub' ],
                                                              '-fields' : { 'super' : '0',
                                                                             'sub' : '1' } },
                                               'sub' : { '-unique' : '',
                                                          '-sequence' : [ 'sub',
                                                                           'super' ],
                                                          '-fields' : { 'super' : '1',
                                                                         'sub' : '0' } } },
                                 '-class' : 'W3C::Rnodes::AclSqlObjects::hierarchy',
                                 '-fieldOrder' : [ 'super',
                                                    'sub',
                                                    'type',
                                                    'sponsor',
                                                    'stops',
                                                    'why',
                                                    'newType',
                                                    'last' ],
                                 '-fields' : { 'why' : { '-size' : '255',
                                                           '-type' : 4,
                                                           '-null' : 1 },
                                                'stops' : { '-size' : '10',
                                                             '-type' : 0,
                                                             '-default' : '0' },
                                                'super' : { '-size' : '10',
                                                             '-type' : 0,
                                                             '-default' : '0' },
                                                'ARRAY(0x844adc4)' : {},
                                                'sponsor' : { '-target' : [ 'ids',
                                                                              'id' ],
                                                               '-size' : '10',
                                                               '-type' : 0,
                                                               '-null' : 1 },
                                                'last' : { '-type' : 10,
                                                            '-null' : 1 },
                                                'newType' : { '-size' : '1',
                                                               '-type' : 3,
                                                               '-null' : 1 },
                                                'type' : { '-size' : '1',
                                                            '-type' : 3,
                                                            '-default' : '' },
                                                'sub' : { '-size' : '10',
                                                           '-type' : 0,
                                                           '-default' : '0' } },
                                 '-primaryKey' : [ 'super',
                                                    'sub' ] },
                'groupDetails' : { '-table' : 'groupDetails',
                                    '-index' : {},
                                    '-class' : 'W3C::Rnodes::AclSqlObjects::groupDetails',
                                    '-fieldOrder' : [ 'id',
                                                       'type',
                                                       'acRep',
                                                       'entityEncoded',
                                                       'alphaname',
                                                       'category',
                                                       'name',
                                                       'notes',
                                                       'last' ],
                                    '-fields' : { 'category' : { '-size' : '100',
                                                                   '-type' : 4,
                                                                   '-null' : 1 },
                                                   'acRep' : { '-size' : '10',
                                                                '-type' : 0,
                                                                '-default' : '0' },
                                                   'entityEncoded' : { '-size' : '255',
                                                                        '-type' : 4,
                                                                        '-default' : '' },
                                                   'alphaname' : { '-size' : '255',
                                                                    '-type' : 4,
                                                                    '-default' : '' },
                                                   'name' : { '-size' : '255',
                                                               '-type' : 4,
                                                               '-default' : '' },
                                                   'last' : { '-type' : 10,
                                                               '-null' : 1 },
                                                   'id' : { '-size' : '10',
                                                             '-type' : 0,
                                                             '-default' : '0' },
                                                   'notes' : { '-size' : "NULL",
                                                                '-type' : 5,
                                                                '-default' : '' },
                                                   'type' : { '-size' : '1',
                                                               '-type' : 3,
                                                               '-null' : 1 } },
                                    '-primaryKey' : 'id' },
                'uris' : { '-table' : 'uris',
                            '-index' : { 'uris_valid' : { '-unique' : '',
                                                            '-sequence' : [ 'valid' ],
                                                            '-fields' : { 'valid' : '0' } },
                                          'i_last' : { '-unique' : '',
                                                        '-sequence' : [ 'last' ],
                                                        '-fields' : { 'last' : '0' } },
                                          'uri_idx' : { '-unique' : '',
                                                         '-sequence' : [ 'uri' ],
                                                         '-fields' : { 'uri' : '0' } },
                                          'uris_acl' : { '-unique' : '',
                                                          '-sequence' : [ 'acl' ],
                                                          '-fields' : { 'acl' : '0' } },
                                          'uri' : { '-unique' : '1',
                                                     '-sequence' : [ 'uri' ],
                                                     '-fields' : { 'uri' : '0' } } },
                            '-class' : 'W3C::Rnodes::AclSqlObjects::uris',
                            '-fieldOrder' : [ 'id',
                                               'uri',
                                               'acl',
                                               'last',
                                               'idsId',
                                               'valid' ],
                            '-fields' : { 'last' : { '-type' : 10,
                                                       '-null' : 1 },
                                           'idsId' : { '-size' : '10',
                                                        '-type' : 0,
                                                        '-null' : 1 },
                                           'valid' : { '-size' : '1',
                                                        '-type' : 3,
                                                        '-default' : 'n' },
                                           'id' : { '-size' : '10',
                                                     '-type' : 0 },
                                           'acl' : { '-size' : '10',
                                                      '-type' : 0,
                                                      '-default' : '0' },
                                           'uri' : { '-size' : '255',
                                                      '-type' : 4,
                                                      '-default' : '' } },
                            '-primaryKey' : 'id' },
                'acls' : { '-table' : 'acls',
                            '-index' : { 'PRIMARY' : { '-unique' : '1',
                                                         '-sequence' : [ 'acl',
                                                                          'id',
                                                                          'access' ],
                                                         '-fields' : { 'access' : '2',
                                                                        'id' : '1',
                                                                        'acl' : '0' } } },
                            '-class' : 'W3C::Rnodes::AclSqlObjects::acls',
                            '-fieldOrder' : [ 'acl',
                                               'id',
                                               'access',
                                               'type',
                                               'last' ],
                            '-fields' : { 'last' : { '-type' : 10,
                                                       '-null' : 1 },
                                           'access' : { '-size' : '10',
                                                         '-type' : 0,
                                                         '-default' : '0' },
                                           'id' : { '-size' : '10',
                                                     '-type' : 0,
                                                     '-default' : '0' },
                                           'type' : { '-size' : '1',
                                                       '-type' : 3,
                                                       '-default' : '' },
                                           'acl' : { '-size' : '10',
                                                      '-type' : 0 } },
                            '-primaryKey' : [ 'acl',
                                               'id',
                                               'access' ] },
                'userDetails' : { '-table' : 'userDetails',
                                   '-index' : {},
                                   '-class' : 'W3C::Rnodes::AclSqlObjects::userDetails',
                                   '-fieldOrder' : [ 'id',
                                                      'family',
                                                      'given',
                                                      'prefix',
                                                      'status',
                                                      'passwd',
                                                      'mailback',
                                                      'email',
                                                      'emailUrisId',
                                                      'phone',
                                                      'position',
                                                      'ac',
                                                      'acEric',
                                                      'url',
                                                      'last',
                                                      'cleartxt',
                                                      'notes',
                                                      'phonesId' ],
                                   '-fields' : { 'acEric' : { '-size' : '10',
                                                                '-type' : 0,
                                                                '-null' : 1 },
                                                  'status' : { '-size' : '10',
                                                                '-type' : 0,
                                                                '-null' : 1,
                                                                '-default' : '0' },
                                                  'ac' : { '-size' : '255',
                                                            '-type' : 4,
                                                            '-null' : 1 },
                                                  'emailUrisId' : { '-target' : [ 'uris',
                                                                                    'id' ],
                                                                     '-size' : '10',
                                                                     '-type' : 0,
                                                                     '-default' : '0' },
                                                  'notes' : { '-size' : "NULL",
                                                               '-type' : 5,
                                                               '-default' : '' },
                                                  'phone' : { '-size' : '32',
                                                               '-type' : 4,
                                                               '-null' : 1 },
                                                  'passwd' : { '-size' : '40',
                                                                '-type' : 4,
                                                                '-null' : 1 },
                                                  'given' : { '-size' : '255',
                                                               '-type' : 4,
                                                               '-default' : '' },
                                                  'cleartxt' : { '-size' : '40',
                                                                  '-type' : 4,
                                                                  '-null' : 1 },
                                                  'phonesId' : { '-size' : '10',
                                                                  '-type' : 0,
                                                                  '-null' : 1 },
                                                  'mailback' : { '-size' : '40',
                                                                  '-type' : 4,
                                                                  '-null' : 1 },
                                                  'url' : { '-size' : '255',
                                                             '-type' : 4,
                                                             '-null' : 1 },
                                                  'position' : { '-size' : '255',
                                                                  '-type' : 4,
                                                                  '-null' : 1 },
                                                  'last' : { '-type' : 10,
                                                              '-null' : 1 },
                                                  'ARRAY(0x8442a7c)' : {},
                                                  'id' : { '-size' : '10',
                                                            '-type' : 0,
                                                            '-default' : '0' },
                                                  'family' : { '-size' : '255',
                                                                '-type' : 4,
                                                                '-default' : '' },
                                                  'email' : { '-size' : '255',
                                                               '-type' : 4,
                                                               '-null' : 1 },
                                                  'prefix' : { '-size' : '255',
                                                                '-type' : 4,
                                                                '-default' : '' } },
                                   '-primaryKey' : 'id' } }

