PREFIX : <http://example/ex#>
PREFIX doc: <http://example/>
SELECT *
WHERE { { GRAPH doc:one {:w :e :r OPTIONAL {GRAPH doc:two { ?x :b :c }}}} UNION { :y :e :r OPTIONAL {?x :r :e}}
#        FILTER (!bound(?x)) 
}
