# ccpp examples as challenged in last call comments
#
all: ex2-2-b.rdf.n3 ex2-2-b.rdf.rdf
	touch all

ex2-2-b.rdf.n3: ex2-2-b.rdf
	cwm --rdf ex2-2-b.rdf --n3 --quiet > ex2-2-b.rdf.n3

ex2-2-b.rdf.rdf: ex2-2-b.rdf
	cwm --rdf ex2-2-b.rdf --quiet > ex2-2-b.rdf.rdf

#ends


