# Diff of big files
#

foo.diff:
	time python2.3 ../../diff.py -f http://lists.w3.org/Archives/Public/www-archive/2004Oct/att-0027/webarch-lc-comments.rdf__charset_us-ascii -t http://lists.w3.org/Archives/Public/www-archive/2004Oct/att-0027/02-webarch-lc-comments.rdf__charset_us-ascii > foo.diff

#ends


